import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "idahagerth",
  description: "Generated by create next app",
};

export function Navbar() {
  return (
    <nav className="fixed top-0 w-full bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <Link href="/" className="font-bold text-xl">
        
          </Link>

          <div className="hidden sm:flex space-x-8">
            <Link
              target="_blank"
              href="https://github.com/idahagerth"
              className="text-stone-800 hover:text-stone-400"
            >
              Github
            </Link>
            <Link
              href="/projects"
              className="text-stone-800 hover:text-stone-400"
            >
              Projects
            </Link>
            <Link
              href="/contact"
              className="text-stone-800 hover:text-stone-400"
            >
              Contact
            </Link>
          </div>
        </div>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
